# Generated by Django 3.0.5 on 2020-05-01 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(max_length=50)),
                ('display_order', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('from_date_bs', models.CharField(max_length=10)),
                ('from_date_ad', models.DateField()),
                ('to_date_bs', models.CharField(max_length=10)),
                ('to_date_ad', models.DateField()),
                ('display_order', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(max_length=50)),
                ('display_order', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalLevelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(max_length=50)),
                ('display_order', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NepaliMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(max_length=50)),
                ('display_order', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(max_length=50)),
                ('display_order', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(max_length=50)),
                ('wards_count', models.IntegerField(null=True)),
                ('gps_lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('gps_long', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('display_order', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_master.District')),
                ('local_level_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_master.LocalLevelType')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_master.Province'),
        ),
    ]
